apiVersion: apps/v1   
kind: Deployment    
metadata:            
  name: node1-deployment    
  labels:        
    app: node1  
spec:            
  replicas: 1
  selector:       
    matchLabels: 
      app: node1
  template:        
    metadata:    
      labels:    
        app: node1
    spec:        
      containers:    
      - name: node1
        image: arboretc/node1:latest
        ports:
          - containerPort: 80
