apiVersion: v1
kind: Service  
metadata:
  name: node1-service
spec:
  selector:    
    app: node1
  ports:  
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: 1.1.1.1
  externalIPs:
    - 10.161.188.250
