apiVersion: apps/v1   
kind: Deployment    
metadata:            
  name: vue-d
  labels:        
    app: vue
spec:            
  replicas: 4
  selector:       
    matchLabels: 
      app: vue
  template:        
    metadata:    
      labels:    
        app: vue
    spec:        
      containers:    
      - name: vue
        image: arboretc/vueex:latest
        ports:
          - containerPort: 8081
