apiVersion: v1
kind: Service  
metadata:
  name: vue-s
spec:
  selector:    
    app: vue
  ports:  
    - port: 8081
      targetPort: 8081
      nodePort: 31110
  type: LoadBalancer
  externalIPs:
    - 10.161.188.250
